# Generated by Django 4.0.2 on 2022-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='player/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='idea.png', upload_to='player/'),
        ),
    ]
