# Generated by Django 4.0.2 on 2022-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=32)),
                ('grado', models.CharField(max_length=32)),
                ('inicio', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=32)),
                ('observacion', models.CharField(max_length=128)),
            ],
        ),
    ]
