# Generated by Django 4.0.2 on 2022-02-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='i',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
