# Generated by Django 4.0.2 on 2022-02-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv', '0002_estudios_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=32)),
                ('puesto', models.CharField(max_length=32)),
                ('inicio', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=128)),
                ('i', models.IntegerField()),
            ],
        ),
    ]
