# Generated by Django 4.0.2 on 2022-02-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv', '0003_trabajos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='descripcion',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='observacion',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='descripcion',
            field=models.CharField(max_length=254),
        ),
    ]
