# Generated by Django 4.0.2 on 2022-02-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv', '0005_estudios_en_trabajos_en_alter_estudios_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudios_en',
        ),
        migrations.DeleteModel(
            name='Trabajos_en',
        ),
        migrations.AddField(
            model_name='estudios',
            name='descripcion_en',
            field=models.TextField(default='Test', max_length=254),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='descripcion_en',
            field=models.TextField(default='Test', max_length=254),
        ),
    ]
